Banner.create(name: "hello", description: "world")
Banner.first.banner_items.create(key_word: "hello", image_id: 1)
Banner.first.banner_items.create(key_word: "world", image_id: 2)
Image.create(link: "xx", from: 1)
Image.create(link: "yy", from: 1)
Image.create(link: "zz", from: 1)
Image.create(link: "oo", from: 1)

Theme.create(name: "jayzen", description: "xx", topic_img_id: 1, head_img_id: 3)
Theme.create(name: "9898", description: "xxdd", topic_img_id: 2, head_img_id: 4)
Category.create(name: "hello", topic_img_id: 1)
Product.create(name: "111", category_id: 1, main_img_url: "xx", price: 10, stock: 20)
Product.create(name: "222", category_id: 1, main_img_url: "yy", price: 2, stock: 10)
ThemeProduct.create(theme_id: 1, product_id: 1)
ThemeProduct.create(theme_id: 1, product_id: 2)
Product.first.product_images.create(img_id: 1)
Product.first.product_images.create(img_id: 2)
Product.first.product_properties.create(name: "hello", detail: "world")
Product.first.product_properties.create(name: "xxx", detail: "yyy")
